source 'http://gemcutter.org'
source 'http://gems.rubyforge.org'
source 'http://rubygems.org'
source 'https://rubygems.org'
gem 'selenium-webdriver'
gem 'mail'
gem 'faker'
gem 'nokogiri'
gem 'selenium-client'

# You can add all gems required to be installed here